// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// get_ev_from_evd
arma::mat get_ev_from_evd(const arma::mat& mat);
RcppExport SEXP _snpsettest_get_ev_from_evd(SEXP matSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type mat(matSEXP);
    rcpp_result_gen = Rcpp::wrap(get_ev_from_evd(mat));
    return rcpp_result_gen;
END_RCPP
}
// get_ev_from_svd
arma::mat get_ev_from_svd(const arma::mat& mat);
RcppExport SEXP _snpsettest_get_ev_from_svd(SEXP matSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type mat(matSEXP);
    rcpp_result_gen = Rcpp::wrap(get_ev_from_svd(mat));
    return rcpp_result_gen;
END_RCPP
}
// match_cpp
IntegerVector match_cpp(CharacterVector x, CharacterVector table);
RcppExport SEXP _snpsettest_match_cpp(SEXP xSEXP, SEXP tableSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< CharacterVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type table(tableSEXP);
    rcpp_result_gen = Rcpp::wrap(match_cpp(x, table));
    return rcpp_result_gen;
END_RCPP
}
