# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

get_ev_from_evd <- function(mat) {
    .Call(`_snpsettest_get_ev_from_evd`, mat)
}

get_ev_from_svd <- function(mat) {
    .Call(`_snpsettest_get_ev_from_svd`, mat)
}

match_cpp <- function(x, table) {
    .Call(`_snpsettest_match_cpp`, x, table)
}

