# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @export
cor_cpp <- function(mat) {
    .Call(`_snpsettest_cor_cpp`, mat)
}

#' @export
match_cpp <- function(x, table) {
    .Call(`_snpsettest_match_cpp`, x, table)
}

